#!/usr/bin/env ansible-playbook

- hosts: all
  become: false

  vars_files:
    - custom.yml

  handlers:
    - import_tasks: handlers/main.yml

  roles:
    - role: system
      when: ansible_connection == "ssh"
      tags:
        - system

    - role: docker
      when: ansible_connection == "ssh"
      tags:
        - docker

    - role: docker-flask-app
      when: deploy_application is defined
      tags:
        - docker-flask-app

